### ISSUE TITLE
/snap/bin/snapcraft: 3: exec: "/snap/snapcraft/current/usr/bin/python3": not found

### ISSUE THREAD

**Issue by antenore** [kenvandine/gnome-3-38-2004#1]
Hi @kenvandine , @sergiusens 

I'm trying to use this docker image to use core20 and the Gnome runtime 3-38 for the Remmina package, but I get this error:

```
/snap/bin/snapcraft: 3: exec: "/snap/snapcraft/current/usr/bin/python3": not found
```

Am I missing something? 

https://gitlab.com/Remmina/Remmina/-/blob/189f95dd0b9588b783e57bf35dbfa5b5055e3315/.gitlab-ci.yml#L101
https://gitlab.com/Remmina/Remmina/-/blob/189f95dd0b9588b783e57bf35dbfa5b5055e3315/snap/snapcraft.yaml

And thanks a lot for maintaining these images!!!

**Comment by kenvandine** [comment]
I haven't gotten this image working yet, I should be able to work on it tomorrow.

**Comment by antenore** [comment]
Thank you Ken!

Take your time and If I can help somehow let me know!!!

**Comment by jhenstridge** [comment]
I think the underlying problem is that the image doesn't include a copy of core18. While we do want a copy of core20 to build snaps that use that base, Snapcraft itself requires core18 to run.  In particular:

```
$ readelf -a /snap/snapcraft/current/usr/bin/python3 | grep core18
      [Requesting program interpreter: /snap/core18/current/lib64/ld-linux-x86-64.so.2]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../../lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu]
```

The confusing "not found" error message is because the `/snap/snapcraft/current/usr/bin/python3` binary has its interpreter set to `/snap/core18/current/lib64/ld-linux-x86-64.so.2`, and that's the file that is not found. It also has its RPATH set to prefer libraries provided by core18 over those from the host system.

**Comment by antenore** [comment]
I thought about this and found something in the snapcraft repository,  or in the forum, I don't remember. 

That would make the image and probably the resulting snap huge.

Maybe we should just wait for a core20 compatible snapcraft ?

**Comment by sergiusens** [comment]
On Tue, Aug 24, 2021 at 2:31 AM Antenore Gatta ***@***.***>
wrote:

> I thought about this and found something in the snapcraft repository, or
> in the forum, I don't remember.
>
> That would make the image and probably the resulting snap huge.
>

This is snapcraft's runtime requirement, not the runtime requirement of
what it builds. If the docker image had core18, snapcraft' runtime
requirement would be satisfied. This is true to run snapcraft using docker
or not with the difference that it is handled transparently for the latter
case.

Maybe we should just wait for a core20 compatible # snapcraft ?
>

That's coming soon, but adding core18 to your docker image should solve
that problem.
Thanks James for looking into this.

**Comment by jhenstridge** [comment]
Yep.  The existing version of Snapcraft is "core20 compatible" in the sense that it will run in a Docker image built from Ubuntu 20.04: it just relies on the core18 files also being present.

Adding the extra snap's files would only increase the size of the Docker image (by maybe 10%?): not the snaps that it produces. We'd be able to remove core18 from the Docker image once Snapcraft is built with core20, but we'd then also need to add core20 to the gnome-3-28-1804 image (assuming people still want to use it).

**Comment by kenvandine** [comment]
This should be fixed now, @antenore can you please give it a try?

**Comment by jhenstridge** [comment]
Here's a successful snap build using the updated Docker image:

https://gitlab.gnome.org/jamesh/gtk-common-themes/-/jobs/1473329

So it looks like this has fixed the problem.

**Comment by antenore** [comment]
Sorry for the long waiting.

I'm trying right now.

**Comment by antenore** [comment]
It was a pain, I've done it.

I'm waiting for the last build to finish and publish the stable snap.

Thanks a lot of guys!

BTW, am I asking too much for a quick review? 😅 

I'm afraid I'm staging too much and not cleaning enough.

https://gitlab.com/Remmina/Remmina/-/blob/master/.gitlab-ci.yml
https://gitlab.com/Remmina/Remmina/-/blob/master/snap/snapcraft.yaml

**Comment by antenore** [comment]
This for example

`
Icon snap.remmina.org.remmina.Remmina specified in desktop file /builds/Remmina/Remmina/prime/usr/share/applications/org.remmina.Remmina.desktop not found in prime directory`

**Comment by kenvandine** [comment]
> It was a pain, I've done it.
> 
> I'm waiting for the last build to finish and publish the stable snap.
> 
> Thanks a lot of guys!
> 
> BTW, am I asking too much for a quick review? sweat_smile
> 
> I'm afraid I'm staging too much and not cleaning enough.
> 
> https://gitlab.com/Remmina/Remmina/-/blob/master/.gitlab-ci.yml
> https://gitlab.com/Remmina/Remmina/-/blob/master/snap/snapcraft.yaml

You are staging way too much as well as using build-packages that should are actually available in the gnome-3-38-2004-sdk build snap.  I'll take a pass at cleaning things up a bit and submit a PR.

**Comment by antenore** [comment]
Much appreciated @kenvandine

**Comment by antenore** [comment]
> > It was a pain, I've done it.
> > I'm waiting for the last build to finish and publish the stable snap.
> > Thanks a lot of guys!
> > BTW, am I asking too much for a quick review? sweat_smile
> > I'm afraid I'm staging too much and not cleaning enough.
> > https://gitlab.com/Remmina/Remmina/-/blob/master/.gitlab-ci.yml
> > https://gitlab.com/Remmina/Remmina/-/blob/master/snap/snapcraft.yaml
> 
> You are staging way too much as well as using build-packages that should are actually available in the gnome-3-38-2004-sdk build snap. I'll take a pass at cleaning things up a bit and submit a PR.

@kenvandine if you give some directions I can try to clean it myself :-p

**Comment by kenvandine** [comment]
@antenore so sorry I dropped this... Here's my branch I had been working on before I got distracted.

https://gitlab.com/kenvandine/Remmina/-/commits/snap_gnome_3_38_cleanup

**Comment by antenore** [comment]
> @antenore so sorry I dropped this... Here's my branch I had been working on before I got distracted.
> 
> https://gitlab.com/kenvandine/Remmina/-/commits/snap_gnome_3_38_cleanup

Hey! No problem at all!! :-) 

Thanks I'll continue and thanks so much!!!
